ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  "brace-expansion@<2": "^1.1.21"
  "brace-expansion@>=2": "^5.0.12"
  "browserslist": "^4.28.7"
  "baseline-browser-mapping": "^2.11.0"
  "@babel/core": "^7.29.6"
  "vite": "^8.0.16"
  "@esbuild-kit/core-utils>esbuild": "^0.25.0"
